create table public.user (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  username character varying not null,
  password character varying not null,
  constraint user_pkey primary key (id)
) TABLESPACE pg_default;

create table public.google_account (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  google_id text not null,
  user_id uuid not null,
  email text not null,
  display_name text not null,
  constraint google_account_pkey primary key (id)
) TABLESPACE pg_default;

create table public.google_oauth_access (
  id uuid not null default gen_random_uuid (),
  access_token bytea not null,
  refresh_token bytea not null,
  access_token_expired_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  refreshed_at timestamp with time zone null,
  account_id uuid not null default gen_random_uuid (),
  constraint google_oauth_access_pkey primary key (id),
  constraint google_oauth_access_account_id_fkey foreign KEY (account_id) references google_account (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.oauth_record (
  id uuid not null default gen_random_uuid (),
  provider text not null,
  state text not null,
  pkce_verifier text not null,
  scopes text[] not null,
  redirect_url text not null,
  created_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone null,
  constraint oauth_records_pkey primary key (id)
) TABLESPACE pg_default;

create table public.gmail_backfill_job (
  id bigint generated by default as identity not null,
  status text not null default 'queued'::text,
  account_id uuid not null,
  thread_upserted bigint not null default '0'::bigint,
  message_inserted bigint not null default '0'::bigint,
  next_page_token text null,
  last_error_code text null,
  last_error_message text null,
  last_error_context text null,
  cancel_reason text null,
  created_at timestamp with time zone not null default now(),
  available_at timestamp with time zone not null default now(),
  started_at timestamp with time zone null,
  cancelled_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  constraint gmail_backfill_jobs_pkey primary key (id),
  constraint gmail_backfill_jobs_account_id_fkey foreign KEY (account_id) references google_account (id) on update RESTRICT on delete RESTRICT
) TABLESPACE pg_default;
