// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GmailBackfillJob struct {
	ID               pgtype.UUID
	Status           string
	AccountID        pgtype.UUID
	ThreadUpserted   int64
	MessageInserted  int64
	NextPageToken    pgtype.Text
	LastErrorCode    pgtype.Text
	LastErrorMessage pgtype.Text
	LastErrorContext pgtype.Time
	CancelReason     pgtype.Text
	CreatedAt        pgtype.Timestamptz
	AvailableAt      pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	ClaimedBy        pgtype.Text
}

type GoogleAccount struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	GoogleID    string
	UserID      pgtype.UUID
	Email       string
	DisplayName string
}

type GoogleOauthAccess struct {
	ID                   pgtype.UUID
	AccessToken          []byte
	RefreshToken         []byte
	AccessTokenExpiredAt pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	RefreshedAt          pgtype.Timestamptz
	AccountID            pgtype.UUID
}

type OauthRecord struct {
	ID           pgtype.UUID
	Provider     string
	State        string
	PkceVerifier string
	Scopes       []string
	RedirectUrl  string
	CreatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Username  string
	Password  string
}
